[package]
edition = "2021"
name = "topics"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
serde_derive = "1.0"
serde_json = "1.0.96"
